# Project: TicTacToe_C++Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o TTT1.o
LINKOBJ  = Main.o TTT1.o
LIBS     = -L"D:/programfile/Dev-Cpp/MinGW64/lib" -L"D:/programfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/programfile/Dev-Cpp/MinGW64/include" -I"D:/programfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/programfile/Dev-Cpp/MinGW64/include" -I"D:/programfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/programfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/programfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TicTacToe_C++Project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.c
	$(CPP) -c Main.c -o Main.o $(CXXFLAGS)

TTT1.o: TTT1.cpp
	$(CPP) -c TTT1.cpp -o TTT1.o $(CXXFLAGS)
